#!/bin/sh
#
# Remove getty logins for a range of TruePort ports
#
# Usage: rmlogins <first> <last>
# <first> is the number of the first port.
# <last> is the number of the last port.
#


PD=/etc/trueport	# Install directory
PLOGIN=$PD/tplogin	# Login script for one port

Usage ()
{
	echo "Usage: $0 <first> <last>"
	exit 1
}


# Validate first port number
if [ "$1" != "" ] && [ "`expr $1 : '\([0-9]*\)'`" = "$1" ]
then
	PNUM=$1
else
	echo "Invalid first port number."
	Usage
fi

# Validate last port number
if [ "$2" != "" ] && [ "`expr $2 : '\([0-9]*\)'`" = "$2" ]
then
	PLAST=$2
else
	echo "Invalid last port number."
	Usage
fi

#
# Create the logins
#
while [ $PNUM -le $PLAST ]
do

	echo $PLOGIN -r $PNUM 
	$PLOGIN -r $PNUM 

	if [ $? -ne 0 ]
	then
		echo "$PLOGIN failed for port $PNUM !"
		echo "$0 aborted"
		exit 1
	fi

	PNUM=`expr $PNUM + 1`
done

exit 0

